const messages=[{user:"User",text:"Hello!"},{user:"Bot",text:"Hi there! How can I help you?"},],isDisplayed=async()=>{let e=document.createElement("button");e.innerHTML="<i class='fas fa-robot'></i>",e.style.display="block !important",e.style.position="fixed",e.style.bottom="20px",e.style.right="20px",e.style.backgroundColor="#3498db",e.style.borderRadius="50%",e.style.height="60px",e.style.width="60px",e.style.color="#fff",e.style.border="none",e.style.padding="10px",e.style.cursor="pointer",e.style.fontSize="20px",e.style.boxShadow="rgb(110 104 104 / 38%) 0px 4px 10px",e.id="wordAiLobittoChatButtonWidget",document.querySelector("body").appendChild(e);let t=document.createElement("div");t.style.display="none",t.style.position="fixed",t.style.bottom="50px",t.style.right="20px",t.style.width="300px",t.style.height="400px",t.style.border="1px solid #ccc",t.style.backgroundColor="#fff",t.style.zIndex="999",t.style.margin="10px",t.style.boxShadow="0 0 10px rgba(0, 0, 0, 0.1)",t.innerHTML=`
    <div style="background-color: #3498db; color: #fff; padding: 10px; border-bottom: 1px solid #ccc; display: flex; justify-content: space-between; align-items: center;">
      <span>Word AI</span>
      <button onclick="closeChat()" style="background: none; border: none; color: #fff; cursor: pointer;">&times;</button>
    </div>
    <div id="chatBody" style="max-height: 300px; overflow-y: auto; padding: 10px;     display: flex;
    flex-direction: column;"></div>
    <div style="position: absolute;padding: 10px;border: 1px solid #dadada;padding: 0;margin: 4px;border-radius: 50px;bottom: 0;right: 0;left: 0;">
      <input onfocus="changeBorderStyle(this)" type="text" id="messageInput" placeholder="Type your message..." style="padding: 8px;border-radius: 50px;border: none;width: 80%;">
      <button id="sendButton" onclick="sendMessage()" style="position: absolute;right: 0px;top: 50%;transform: translateY(-50%);background-color: #3498db;color: #fff;border: none;/* padding: 8px; */cursor: pointer;border-radius: 50%;height: 30px;width: 30px;display: flex;justify-content: center;align-items: center;">
        <i class="fas fa-paper-plane"></i> <!-- Font Awesome send icon -->
      </button>
    </div>
  `,document.body.appendChild(t),displayMessages(messages),e.addEventListener("click",()=>{t.style.display="none"===t.style.display?"block":"none"})};function changeBorderStyle(e){e.style.outline="none"}function displayMessages(e){let t=document.getElementById("chatBody");t.innerHTML="",e.forEach(e=>{let s=document.createElement("div");s.textContent=`${e.text}`,e.user,s.style.padding="8px",s.style.borderRadius="User"===e.user?"5px 5px 5px 0":"5px 5px 0 5px",s.style.backgroundColor="User"===e.user?"#3498db":"#f1f1f1",s.style.color="User"===e.user?"#fff":"#333",s.style.marginBottom="8px",s.style.maxWidth="85%",s.style.wordWrap="break-word",s.style.alignSelf="User"===e.user?"flex-end":"flex-start",t.appendChild(s)}),t.scrollTop=t.scrollHeight}function closeChat(){chatWidget.style.display="none"}async function sendMessage(){let e=document.getElementById("messageInput"),t=e.value.trim();if(""!==t){let s=document.getElementById("sendButton");s.disabled=!0,s.style.backgroundColor="#d8d8d8",s.style.color="#333",s.innerHTML='<i class="fas fa-spinner fa-spin"></i>';try{let o=await fetch("http://localhost:8400/api/v3/model/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:t,newChat:!1,conversationID:"NothAvailable"})});if(o.ok){let l=await o.json();console.log(l),messages.push({user:"User",text:t}),messages.push({user:"Bot",text:l?.data?.answer}),displayMessages(messages)}else console.error("Error sending message:",o.status)}catch(n){console.error("Error:",n)}finally{s.disabled=!1,s.style.backgroundColor="#3498db",s.style.color="#fff",s.innerHTML='<i class="fas fa-paper-plane"></i>',e.value=""}}}isDisplayed(),setInterval(()=>{console.log("Try again");try{document.getElementById("wordAiLobittoChatButtonWidget")||isDisplayed()}catch(e){}},4e3);
